### PR TITLE
Fixed copy and paste errors from "Support Native Abstractions for Node 2.x"

### PR DESCRIPTION
**Pull request by sweetpi**
Seems to be the missing piece to get it ready for node v4?

### CODE REVIEW

**Comment by stephenwvickers** [comment]
Hi,

Thank you for the patch - I was already aware of this issue.

I almost completed the work, but got side tracked on another work related issue.

Steve

**Comment by stephenwvickers** [comment]
I should be able to complete this tomorrow morning, if all goes well.

**Comment by sweetpi** [comment]
nice :)

**Comment by stephenwvickers** [comment]
Already fixed in source.

**Pull request closed without merging**
